name: Build and Publish RC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    tags:
    # REMOVE WORKFLOWTEST
      - 'WORKFLOWTEST-v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

# To test workflow updates you need to work in a branch directly on viamrobotics/rplidar
# and tag your working branch instead of @main in any viamrobotics/rplidar "uses" below.
# Don't forget to tag back to @main before merge.

jobs:
  appimage:
    # REMOVE WORKFLOWTEST
    uses: viamrobotics/rplidar/.github/workflows/appimage.yml@workflowtest
    with:
      release_type: 'rc'
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
